server:
  port: 8080

## SqlServer 配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://121.36.158.185:1433;databasename=MyTestDB
    username: sa
    password: chen@520J

  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    check-template-location: true
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.xsyy.form.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
